### ISSUE TITLE
http://apache.cs.uu.nl/dist/ is no longer available

### ISSUE THREAD

**Issue by tauceti2** [OpenConext/OpenConext-vm#29]
Hi, 

In scripts/dependencies/maven_install.sh there is URL pointing to http://apache.cs.uu.nl/dist/..., but dist directory no longer exists. If you just remove 'dist' from the URL everything works.

Cheers,

Michal P.

**Comment by relaxnow** [comment]
This has been fixed in https://github.com/OpenConext/OpenConext-vm/issues/28 and will be available in the next release.
